name: Publish to Nexus
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17  # Adjust the Java version as per your project requirements

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Publish
      run: mvn clean deploy --settings settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
